version: "3.9"

services:
  api:
    build: .
    container_name: sentinel5p-api
    restart: always
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8121:8000"
    volumes:
      - /opt/sentinel5p/data:/data
      - /opt/sentinel5p/output:/output
      - /opt/sentinel5p/text.json:/app/text.json:ro
      - /opt/sentinel5p/polygons:/polygons:ro
      - /opt/sentinel5p/geojson/uzbekistan_regions_backup.geojson:/geojson/uzbekistan_regions_backup.geojson:ro
      - /opt/sentinel5p/geojson/uzb_polygon.geojson:/geojson/uzb_polygon.geojson:ro
      - /opt/sentinel5p/logs:/app/logs
      - /opt/sentinel5p/earthengine:/root/.config/earthengine:ro
    networks:
      - sentinel-net

  sentinel-ads:
    build: .
    container_name: sentinel5p-ads
    restart: always
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    command: python -u download_ads.py
    volumes:
      - /home/temur/Documents/Work/goo/output:/output
      - /opt/sentinel5p/logs:/app/logs
      - /opt/sentinel5p/.cdsapirc:/root/.cdsapirc:ro
    networks:
      - sentinel-net

  sentinel-gases:
    build: .
    container_name: sentinel5p-gases
    restart: always
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    command: python -u download_all.py
    volumes:
      - /opt/sentinel5p/data:/data
      - /opt/sentinel5p/logs:/app/logs
      - /opt/sentinel5p/earthengine:/root/.config/earthengine:ro
    networks:
      - sentinel-net

  sentinel-temperature:
    build: .
    container_name: sentinel5p-temperature
    restart: always
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    command: python -u temp.py
    volumes:
      - /opt/sentinel5p/data:/data
      - /opt/sentinel5p/logs:/app/logs
      - /opt/sentinel5p/earthengine:/root/.config/earthengine:ro
    networks:
      - sentinel-net

  sentinel-wind:
    build: .
    container_name: sentinel5p-wind
    restart: always
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    command: python -u wind.py
    volumes:
      - /opt/sentinel5p/data:/data
      - /opt/sentinel5p/output:/output
      - /opt/sentinel5p/logs:/app/logs
      - /opt/sentinel5p/earthengine:/root/.config/earthengine:ro
    networks:
      - sentinel-net

  # ===============================
  #   MINIO (S3)
  # ===============================
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    env_file: .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9021"
    ports:
      - "9000:9000"
      - "9021:9001"
    volumes:
      - minio_data:/data
    networks:
      - sentinel-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "8110:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - sentinel-net

  send:
    build: .
    container_name: sentinel5p-send
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    command: python -u send.py
    volumes:
      - /opt/sentinel5p/data:/data:ro
      - /opt/sentinel5p/output:/output:ro
      - /opt/sentinel5p/logs:/app/logs
    networks:
      - sentinel-net
    restart: "no"

volumes:
  minio_data:

networks:
  sentinel-net:
    driver: bridge
