sonar.projectKey=sentinel5
sonar.projectName=Sentinel 5
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/data/**, **/__pycache__/**, **/*.tif

sonar.python.version=3.10

sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.test.exclusions=**/__pycache__/**

sonar.python.coverage.reportPaths=coverage.xml

# ОБЯЗАТЕЛЬНО
sonar.host.url=http://localhost:9101
sonar.login=sqp_54529aa1d479cae570722e656bdef7ac845b5c0d


