sonar.projectKey=sentinel5
sonar.projectName=Sentinel 5
sonar.projectVersion=1.0

# Исходный код (БЕЗ тестов)
sonar.sources=.
sonar.exclusions=tests/**,**/data/**,**/__pycache__/**,**/*.tif

# Тесты
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

# Python
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml

# SonarQube
sonar.host.url=http://localhost:9104
sonar.token=${SONAR_TOKEN}

